### ISSUE TITLE
trying to use it 

### ISSUE THREAD

**Issue by sebs** [krampstudio/chai-xml#4]
node 9.5.0
latest mocha 

```
var chai    = require('chai');
var expect  = require('chai').expect;
var chaiXml = require('chai-xml');


describe('envelope get-counties', function() {
  var xml = null;
  beforeEach(function() {
    xml = envelope(params, config);
  });

  it('is valid', function() {
    expect(xml).xml.to.be.valid();
  });
});

```

Error:      Error: Invalid Chai property: xml. Did you mean "all"?
      at Object.proxyGetter [as get] (node_modules/chai/lib/chai/utils/proxify.js:63:17)
      at Context.<anonymous> (test/soap/envelopes/get-countries.js:21:16)

**Comment by krampstudio** [comment]
Chai plugins has to be loaded  : 

```js
var chai    = require('chai');
var expect  = require('chai').expect;
var chaiXml = require('chai-xml');

//loads the plugin
chai.use(chaiXml);

describe('envelope get-counties', function() {
...
```

**Comment by sebs** [comment]
ty
